<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>





<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_aloHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
$_aloCategory = $this->helper('Magiccart\Alothemes\Helper\Category');
?>
<?php if (!$_productCollection->count()) : ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else : ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $showAddto = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

        echo $_aloHelper->getGridStyle('.product-items .product-item'); // Config Product Grid

    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $showAddto = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>

    <div class="category-products clearfix products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) : ?>
                <?php /* @escapeNotVerified */ echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info category-products-grid" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image 
                    ?>
                    <div class="images-container">
                        <?php
                        $product_label = $_aloHelper->getLabels($_product);
                        echo $product_label ? '<div class="product-label">' . $product_label . '</div>' : '';
                        ?>
                        <div class="product-hover">
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                            </a>
                            
                            <!--  -->
                            <?php if ($block->getMode() == 'list') : ?>
                                <div class="link-view">
                                <button type="button" class="quickview <?php echo $_product->getTypeId() ?> action-product"
                                    title="<?php echo $block->escapeHtml(__('Quick View')); ?>"
                                    onclick="jQuery.fn.quickview({url:'<?php echo $this->getUrl('alothemes/product/view', array('id' => $_product->getId(), '_type' => 'direct_link', '_secure'=>$this->getRequest()->isSecure()) ) ?>'});">
                                        <span class="lnr lnr-magnifier"></span> 
                                </button>
                                </div>
                            <?php endif; ?>
                            <!--  -->
                            <?php if ($block->getMode() == 'grid') : ?>
                                <div class="hover-box clearfix">
                                    <div class="product actions product-item-actions show-box" <?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                        <div class="tool-action-product">
                                            <div class="link-view">
                                                <button type="button" class="quickview <?php echo $_product->getTypeId() ?> action-product"
                                                    title="<?php echo $block->escapeHtml(__('Quick View')); ?>"
                                                    onclick="jQuery.fn.quickview({url:'<?php echo $this->getUrl('alothemes/product/view', array('id' => $_product->getId(), '_type' => 'direct_link', '_secure'=>$this->getRequest()->isSecure()) ) ?>'});">
                                                        <span class="lnr lnr-magnifier"></span>
                                                </button>
                                            </div>
                                            <!--  -->
                                            <div data-role="add-to-links" class="actions-secondary add-to-links"
                                                <?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                                <?php  $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                <button type="button" class="action-product" tabindex="0"> 
                                                    <a href="#" class="action towishlist"
                                                        title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                        aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                        data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                        data-action="add-to-wishlist" role="button">
                                                        <span class="lnr lnr-heart"></span>
                                                    </a>
                                                </button>
                                            </div>
                                            <!--  -->
                                            <div data-role="add-to-links" class="actions-secondary add-to-links"
                                                <?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                <button type="button" class="action-product" tabindex="0"> 
                                                    <a href="#" class="action tocompare"
                                                        title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                        aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                        data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                                        role="button">
                                                        <span class="lnr lnr-sync"></span>
                                                    </a>
                                                </button>
                                            </div>
                                            <!--  -->
                                            <?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>
                                            <!--  -->
                                        </div>
                                    </div>
                                </div>
                                <?php
                                // $categoryIds = $_product->getCategoryIds();
                                // $categoryId  = count($categoryIds) ? current($categoryIds) : 0;
                                // $category    = $categoryId ? $_aloCategory->getCategory($categoryId) : '';
                                // echo $category ? '<h3 class="category_name"><a href="' . $category->getUrl() . '">' . $category->getName() . '</a></h3>' : '';
                                ?>
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <div class="product details product-item-details products-textlink clearfix">
                                    <h2 class="product name product-name product-item-name">
                                        <a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </h2>
                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                    

                                    <?php 
                                        if($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){
                                            echo $block->getProductPrice($_product);
                                            $_children = $_product->getTypeInstance()->getUsedProducts($_product);
                                            foreach ($_children as $child){
                                                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                                $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
                                                ?>
                                                <div class="price-box price-final_price <?php echo "p".$child->getData('package') ?>" data-role="priceBox" data-product-id="282" data-price-box="product-id-282" style="display: none;">
                                                    <span class="normal-price"> 
                                                        <span class="price-container price-final_price tax weee"> 
                                                            <span class="price-label">As low as</span> 
                                                            <span id="product-price-282" data-price-amount="25" data-price-type="finalPrice" class="price-wrapper ">
                                                                <input type="hidden" name="specialPrice" value="<?php echo $priceHelper->currency($child->getData('special_price'), true, false); ?>">
                                                                <span class="price"><?php echo $priceHelper->currency($child->getData('special_price'), true, false); ?></span>
                                                            </span> 
                                                        </span>
                                                    </span> 
                                                    <span class="old-price"> 
                                                        <span class="price-container price-final_price tax weee"> 
                                                            <span class="price-label">Regular Price</span> 
                                                            <span id="old-price-282" data-price-amount="35" data-price-type="oldPrice" class="price-wrapper ">
                                                                <input type="hidden" name="normalPrice" value="<?php echo $priceHelper->currency($child->getData('price'), true, false); ?>">
                                                                <span class="price"><?php echo $priceHelper->currency($child->getData('price'), true, false); ?></span>
                                                            </span> 
                                                        </span> 
                                                    </span>
                                                </div>
                                                <?php       
                                                }
                                            }else{
                                                echo $block->getProductPrice($_product);
                                            }
                                        ?>

                                </div>

                                <div class="actions-primary actions-cart"
                                    <?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form"
                                        action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>"
                                        method="post">
                                        <input type="hidden" name="product"
                                            value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                        <input type="hidden"
                                            name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                            value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                        <?php echo $block->getBlockHtml('formkey')?>
                                        <!-- <input type="number" class="validate-greater-than-zero" name="qty" value="1"> -->
                                        
                                        <?php 
                                            $_objectManager= \Magento\Framework\App\ObjectManager::getInstance();
                                            $productTypeInstance = $_objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
                                            $productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($_product);
                                            if (!empty($productAttributeOptions)) { //check if product has custom options. If it doesn't go to the next product
                                                foreach($productAttributeOptions as $productAttributeOption){
                                                    ?>
                                                        <p><span><?php echo $productAttributeOption['label']; ?></span></p>
                                                        <select name="super_attribute[<?php echo $productAttributeOption['attribute_id'] ?>]" data-selector="super_attribute[151]" data-validate="{required:true}" id="attribute151" class="super-attribute-select" aria-required="true">
                                                            <?php
                                                                foreach($productAttributeOption['values'] as $configure_option)
                                                                {
                                                                    ?>
                                                                    <option value="<?php echo $configure_option['value_index']; ?>"><?php echo $configure_option['label'] ?></option>
                                                                    <?php
                                                                }
                                                            ?>
                                                            
                                                        </select>
                                                    <?php
                                                }
                                            }
                                        ?>

                                        <?php echo $this->getLayout()
                                                ->createBlock('Magento\Framework\View\Element\Template')
                                                ->setProduct($_product)
                                                ->setTemplate('Magiccart_Alothemes::increase_reduced_qty2.phtml')
                                                ->toHtml(); ?>
                                        <button type="submit"
                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                            class="action tocart primary button btn-cart pull-left-none action-product">
                                            <span class="lnr lnr-cart"></span>
                                        </button>
                                    </form>
                                    <?php else: ?>
                                    <?php if ($_product->getIsSalable()): ?>
                                        <div class="stock available">
                                            <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
                                        </div>
                                    <?php else: ?>
                                        <div class="stock unavailable">
                                            <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
                                        </div>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php if ($block->getMode() == 'list') : ?>
                        <div class="product details product-item-details  products-textlink clearfix">
                            <?php
                            // $categoryIds = $_product->getCategoryIds();
                            // $categoryId  = count($categoryIds) ? current($categoryIds) : 0;
                            // $category    = $categoryId ? $_aloCategory->getCategory($categoryId) : '';
                            // echo $category ? '<h3 class="category_name"><a href="' . $category->getUrl() . '">' . $category->getName() . '</a></h3>' : '';
                            ?>
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <h2 class="product name product-name product-item-name">
                                <a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </h2>
                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                            <?php if ($block->getMode() == 'list') : ?>
                                <div class="product attribute">
                                    <strong class="type"><?php /* @escapeNotVerified */ echo __('Sku:') ?></strong>
                                    <div class="value"><?php /* @escapeNotVerified */ echo $_product->getSku() ?></div>
                                </div>
                                <div class="actions-primary actions-cart"
                                    <?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form"
                                        action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>"
                                        method="post">
                                        <input type="hidden" name="product"
                                            value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                        <input type="hidden"
                                            name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                            value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                        <?php echo $block->getBlockHtml('formkey')?>
                                        <!-- <input type="number" class="validate-greater-than-zero" name="qty" value="1"> -->
                                        
                                        <?php 
                                            $_objectManager= \Magento\Framework\App\ObjectManager::getInstance();
                                            $productTypeInstance = $_objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
                                            $productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($_product);
                                            if (!empty($productAttributeOptions)) { //check if product has custom options. If it doesn't go to the next product
                                                foreach($productAttributeOptions as $productAttributeOption){
                                                    ?>
                                                        <p><span><?php echo $productAttributeOption['label']; ?></span></p>
                                                        <select name="super_attribute[<?php echo $productAttributeOption['attribute_id'] ?>]" data-selector="super_attribute[151]" data-validate="{required:true}" id="attribute151" class="super-attribute-select" aria-required="true">
                                                            <?php
                                                                foreach($productAttributeOption['values'] as $configure_option)
                                                                {
                                                                    ?>
                                                                    <option value="<?php echo $configure_option['value_index']; ?>"><?php echo $configure_option['label'] ?></option>
                                                                    <?php
                                                                }
                                                            ?>
                                                            
                                                        </select>
                                                    <?php
                                                }
                                            }
                                        ?>

                                        <?php echo $this->getLayout()
                                                ->createBlock('Magento\Framework\View\Element\Template')
                                                ->setProduct($_product)
                                                ->setTemplate('Magiccart_Alothemes::increase_reduced_qty2.phtml')
                                                ->toHtml(); ?>
                                        <button type="submit"
                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                            class="action tocart primary button btn-cart pull-left-none action-product">
                                            <span class="lnr lnr-cart"></span>
                                        </button>
                                    </form>
                                    <?php else: ?>
                                    <?php if ($_product->getIsSalable()): ?>
                                        <div class="stock available">
                                            <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
                                        </div>
                                    <?php else: ?>
                                        <div class="stock unavailable">
                                            <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
                                        </div>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div class="product-item-inner">
                                    <?php if ($showDescription) : ?>
                                        <div class="product description product-item-description">
                                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>" class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                                <?php echo $block->getProductDetailsHtml($_product); ?>
                            <?php endif; ?>
                        </div>
                        <div class="product details product-item-details-right  products-textlink clearfix">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <?php 
                            if($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){
                                echo $block->getProductPrice($_product);
                                $_children = $_product->getTypeInstance()->getUsedProducts($_product);
                                foreach ($_children as $child){
                                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                    $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
                                    ?>
                                    <div class="price-box price-final_price <?php echo "p".$child->getData('package') ?>" data-role="priceBox" data-product-id="282" data-price-box="product-id-282" style="display: none;">
                                        <span class="normal-price"> 
                                            <span class="price-container price-final_price tax weee"> 
                                                <span class="price-label">As low as</span> 
                                                <span id="product-price-282" data-price-amount="25" data-price-type="finalPrice" class="price-wrapper ">
                                                    <input type="hidden" name="specialPrice" value="<?php echo $priceHelper->currency($child->getData('special_price'), true, false); ?>">
                                                    <span class="price"><?php echo $priceHelper->currency($child->getData('special_price'), true, false); ?></span>
                                                </span> 
                                            </span>
                                        </span> 
                                        <span class="old-price"> 
                                            <span class="price-container price-final_price tax weee"> 
                                                <span class="price-label">Regular Price</span> 
                                                <span id="old-price-282" data-price-amount="35" data-price-type="oldPrice" class="price-wrapper ">
                                                    <input type="hidden" name="normalPrice" value="<?php echo $priceHelper->currency($child->getData('price'), true, false); ?>">
                                                    <span class="price"><?php echo $priceHelper->currency($child->getData('price'), true, false); ?></span>
                                                </span> 
                                            </span> 
                                        </span>
                                    </div>
                                    <?php       
                                }
                            }else{
                                echo $block->getProductPrice($_product);
                            }
                            ?>
                            <?php if ($_product->getIsSalable()) : ?>
                                <div class="stock available"><label><?php /* @escapeNotVerified */ echo __('Availability:') ?>
                                    </label><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                            <?php else : ?>
                            <?php endif; ?>
                            <?php if ($showAddto) : ?> <?php /* @showAddto */ ?>
                                <div class="product-item-inner">
                                    <div class="product actions-no product-item-actions clearfix" <?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                        <div class="actions-primary" <?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?> style="display: none;">
                                            <?php if ($_product->isSaleable()) : ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">

                                                    <?php echo $block->getBlockHtml('formkey') ?>
                                                    <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary button btn-cart">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else : ?>
                                                <?php if ($_product->getIsSalable()) : ?>
                                                    <div class="stock available">
                                                        <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else : ?>
                                                    <div class="stock unavailable">
                                                        <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links" class="actions-secondary add-to-links" <?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                                <a href="#" class="action towishlist link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
                                                    <!-- <i class="fa fa-heart-o icon"></i> -->
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                            <?php
                                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                            ?>
                                            <a href="#" class="action tocompare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>' role="button">
                                                <!-- <i class="fa fa-exchange icon"></i> -->
                                                <span><?php echo __('Add to Compare') ?></span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; /* End showAddto */ ?>
                        </div>
                    <?php endif; ?>
                </div>
                <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <!-- <div class="toolbar-bottom "> -->
    <div class="toolbar-bottom toolbar-view-<?php echo $viewMode; ?>">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <!-- </div> -->
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
    </script>
    <?php endif; ?>
<?php endif; ?>
<?php if ($block->getMode() == 'grid'): ?>
<script type="text/javascript">
    require(['jquery'], function($) {
        $('.super-attribute-select').on('change', function(){
            // console.log($(this).val());
            $(this).parents(".product-item").find('.price-box.price-final_price').css("display", "none");
            var specialPrice = $(this).parents(".product-item").find('.price-box.price-final_price.p'+$(this).val()+' input[name="specialPrice"]').val();

            var normalPrice = $(this).parents(".product-item").find('.price-box.price-final_price.p'+$(this).val()+' input[name="normalPrice"]').val();
            // console.log(specialPrice);
            // console.log(normalPrice);
            $(this).parents(".product-item").find('.product-item-details').append('<div class="price-box price-final_price data-role="priceBox" data-product-id="282" data-price-box="product-id-282"><span class="normal-price"><span class="price-container price-final_price tax weee"><span class="price-label">As low as</span><span id="product-price-282" data-price-amount="25" data-price-type="finalPrice" class="price-wrapper "><span class="price">'+specialPrice+'</span></span></span></span><span class="old-price"><span class="price-container price-final_price tax weee"><span class="price-label">Regular Price</span><span id="old-price-282" data-price-amount="35" data-price-type="oldPrice" class="price-wrapper "><span class="price">'+normalPrice+'</span></span></span></div>');
        })
    });
</script>
<?php else: ?>
<script type="text/javascript">
    require(['jquery'], function($) {
        $('.super-attribute-select').on('change', function(){
            // console.log($(this).val());
            $(this).parents(".product-item").find('.price-box.price-final_price').css("display", "none");
            var specialPrice = $(this).parents(".product-item").find('.price-box.price-final_price.p'+$(this).val()+' input[name="specialPrice"]').val();

            var normalPrice = $(this).parents(".product-item").find('.price-box.price-final_price.p'+$(this).val()+' input[name="normalPrice"]').val();
            // console.log(specialPrice);
            // console.log(normalPrice);
            $(this).parents(".product-item").find('.product-item-details-right').prepend('<div class="price-box price-final_price data-role="priceBox" data-product-id="282" data-price-box="product-id-282"><span class="normal-price"><span class="price-container price-final_price tax weee"><span class="price-label">As low as</span><span id="product-price-282" data-price-amount="25" data-price-type="finalPrice" class="price-wrapper "><span class="price">'+specialPrice+'</span></span></span></span><span class="old-price"><span class="price-container price-final_price tax weee"><span class="price-label">Regular Price</span><span id="old-price-282" data-price-amount="35" data-price-type="oldPrice" class="price-wrapper "><span class="price">'+normalPrice+'</span></span></span></div>');
        })
    });
</script>
<?php endif; ?>